name: Nuttx-esp32 QEMU

permissions:
  ## Allow publishing of GitHub Release
  contents: read
on: 
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/nuttx_esp32.yml'

jobs:
  nuttx-esp32:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          update: false
          install: >-
            base-devel
            gcc
            gperf
            git
            python3
            ncurses-devel
            unzip
            zip
            tio
            zlib-devel
            cmake
            ninja
            python-pip 
            vim
            curl

      - name: pip3 install
        run: |
          echo 'pip3 install'
          uname
          pip3 install --root-user-action=ignore --no-cache-dir pyelftools cxxfilt kconfiglib
          
      - name: Checkout Source Files
        run: |
          echo 'Checkout Source Files'
          mkdir nuttxspace
          ls -a
          cd nuttxspace
          ## git clone https://github.com/apache/incubator-nuttx nuttx
          ## git clone https://github.com/apache/incubator-nuttx-apps apps
          git clone --single-branch --branch simbit18-20240306 https://github.com/simbit18/nuttx.git nuttx
          git clone --single-branch --branch simbit18-20240306 https://github.com/simbit18/nuttx-apps.git apps
          ## curl -L https://www.apache.org/dyn/closer.lua/nuttx/12.0.0/apache-nuttx-12.0.0.tar.gz?action=download -o nuttx.tar.gz
          ## curl -L https://www.apache.org/dyn/closer.lua/nuttx/12.0.0/apache-nuttx-apps-12.0.0.tar.gz?action=download -o apps.tar.gz
          ## tar zxf nuttx.tar.gz --one-top-level=nuttx --strip-components 1
          ## tar zxf apps.tar.gz --one-top-level=apps --strip-components 1
          ## ls -a
          ## cd nuttx
          echo 'Copy tools'
          cp -f ../../tools/esp32/install_tools_esp.sh install_tools_esp.sh
          ls -a
          ./install_tools_esp.sh

      - name: Build
        run: |
          echo 'Build'

          ## Move to nuttx
          cd nuttxspace/nuttx
          ls -a

          ## Show the GCC version
          gcc -v
          ## ls -a ../../
          ## cp -f ../../fix/1200/defconfig boards/sim/sim/sim/configs/nsh/defconfig
          ## cp -f ../../fix/1200/sim_hostmisc.c arch/sim/src/sim/posix/sim_hostmisc.c
          ## cp -f ../../fix/1200/lib_exit.c libs/libc/stdlib/lib_exit.c
          
          ## Configure the build
          ####./tools/configure.sh -g sim:nsh
          
          ## mkdir nuttxmsys2
          
          ## Preserve the build config
          ## cp .config nuttxmsys2/nuttx.config
          ######make -j 4
          ls -a
          ## cp nuttx.exe nuttxmsys2/nuttx.exe
          ## cp System.map nuttxmsys2/System.map
          ## cp /usr/bin/msys-2.0.dll nuttxmsys2/msys-2.0.dll
          ## cp /usr/bin/msys-z.dll nuttxmsys2/msys-z.dll
          ## zip -r nuttxmsys2.zip nuttxmsys2
